index.js
This change will force code like:
```js
if (typeof p === 'string') p = { src: p }
```
To be always written in a proper block:
```js
if (typeof p === 'string') {
p = { src: p }
}
```
I think lonely ifs are a bad pattern in keeping the code as maintainable as possible. 
This change will require a subsequent PR to nuxt.js itself to fix offending occurrences.
Already have a branch with it, just waiting for this to be approved first -- that is, if I can get you guys to agree with me :)
=> chore: change curly rule to prevent lonely ifs

index.js, tests/basic.test.js
Hi, I'm a huge fan of Nuxt.js and recently I generated new Nuxt.js project with `create-nuxt-app`.
I found `create-nuxt-app` sets up ESLint with `@nuxtjs/eslint-config` and I think this is a great idea because everyone who starts to develop Nuxt.js application needs less laborious setting up processes.
That's why I strongly insist that changing basic StandardJS rules must be avoided.
Please customize your rules only with your terminatory project, not with commonly used library.
=> Please avoid changing basic StandardJS rules

README.md, index.js, package.json, tests/basic.test.js, tests/validate-config.test.js, yarn.lock
resolves #34 
Please go through the changes and leave feedback :relaxed: 
I tried to be not that strict to avoid errors in existing code bases and with 3rd party libs (e.g. by not preventing abbreviations)
EDIT: Though the last test is failing, the rules do work :thinking:
=> feat: unicorn rules

index.js
Instead of turning off no-console in development and displaying error in production, it would be better to show some warning message for development usage.
Why not turning it off or use `error` in development:
- App won't be broken if user adds `console.log` in dev mode with `eslint-loader`
- User can still get warning messages for inappropriate usage instead of a sudden error in ci building or pr checking.
Resolves https://github.com/nuxt/create-nuxt-app/issues/301
=> feat: warn console and debugger in dev

packages/eslint-config-typescript/index.js
Docs say:
>We strongly recommend that you do not use the no-undef lint rule on TypeScript projects. The checks it provides are already provided by TypeScript without the need for configuration - TypeScript just does this significantly better.
Closes #140
=> fix: turn off typescript 'no-undef' rule per docs

README.md
See https://github.com/babel/babel-eslint#note-babel-eslint-is-now-babeleslint-parser-and-has-moved-into-the-babel-monorepo
=> docs: replace babel-eslint with @babel/eslint-parser

packages/eslint-config/package.json, yarn.lock
`eslint-plugin-standard` was deprecated with v16 of `eslint-config-standard` as it is no longer necessary.
More info:
- https://www.npmjs.com/package/eslint-plugin-standard
- https://github.com/standard/standard/issues/1316
Feel free to request any changes you need me to do to get this merged 👍
=> fix: remove dependency on `eslint-plugin-standard`

packages/eslint-config/index.js
Not ideal for page components :( 
Resolves #192 
Better would be disabling it for the pages folder only I'd say 😋
=> chore: disable multiword-rule

packages/eslint-config/index.js
=> fix: disable vue/multi-word-component-names for files in subdirectories

README.md
```
> eslint .
Oops! Something went wrong! :(
ESLint: 8.33.0
ESLint couldn't find the config "@nuxtjs" to extend from. Please check that the name of the config is correct.
The config "@nuxtjs" was referenced from the config file in "/Users/iam/projects/demo-nuxt/.eslintrc".
If you still have problems, please stop by https://eslint.org/chat/help to chat with the team.
```
=> docs(readme): update extends examples

packages/eslint-config/index.js
Hi
I thought since the components in subfolders of components folder are automatically loaded with prefixed name of the folders out of the box, it should also ignore the naming rules in the subfolders
I thought it would be nice, so I made a PR
=> fix: exclude subfolders of components folder from name rule

README.md
The section describing the @nuxtjs/eslint-config package use has a typo in it's code snippet. This PR corrects the typo in code snippet to extend ESlint config correctly
=> docs: fix typo in package name

README.md
... as they seem to have overhauled their README respectively documentation.
=> docs: add new link to typescript-eslints supported rules

README.md
Clarify headings for Nuxt3 vs Nuxt2 usage in README
Part of #311: Note that I did keep the section for now, maybe there are better approaches (having 2 README? Completely remove references to Nuxt2 config?)
May also close #309
Also note that the various npmjs.com pages does not display any README information, which is also kind of confusing:
- https://www.npmjs.com/package/@nuxtjs/eslint-config (was not published for a year, is there anything broken with the deployment?)
- https://www.npmjs.com/package/@nuxtjs/eslint-config-typescript (was published 4 months ago)
- https://www.npmjs.com/package/@nuxt/eslint-config (was published 4 months ago)
=> :memo: Improve README on Nuxt3 vs Nuxt2 usage

packages/eslint-config/src/flat/configs/disables.ts
context: https://github.com/danielroe/roe.dev/commit/3baf8d44c5a4b30c7e3c69daab4d7ab3ff27a087#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2R20-R25
=> fix(eslint-config): handle `app.vue` and `error.vue` in custom `srcDir`

eslint.config.js, packages/eslint-config/package.json, packages/eslint-config/src/flat/configs/disables.ts, packages/eslint-config/src/flat/configs/nuxt.ts, packages/eslint-config/src/flat/configs/vue.ts, packages/eslint-config/src/flat/index.ts, packages/eslint-config/src/flat/types.ts, packages/eslint-config/src/flat/utils.ts, packages/module/package.json, packages/module/src/modules/config.ts, pnpm-lock.yaml
This would allow direct configure usage easier by auto inferring the subfolder with Nuxt 3's default. Later for nuxt 4 we could have an option for different defaults.
=> feat(eslint-config): support for multiple src dirs and auto infer directories structure

packages/eslint-config/src/flat/index.ts
This pull request introduces the implementation of the proposed `name` field within the `@stylistic/eslint-plugin` configuration, addressing the [feature request](https://github.com/nuxt/eslint/issues/373) for enhanced configuration clarity and simplicity. By integrating a `name` field, we enable users to directly and intuitively identify and modify the configuration.
**Changes Made:**
- Added a `name` field to the configuration objects within `@stylistic/eslint-plugin`, allowing for straightforward identification.
**Benefits:**
- **Improved Clarity:** Directly identifying configurations by name enhances the understandability of the configuration process.
- **Reduced Complexity:** Eliminates the need to inspect the plugins array, simplifying the configuration adjustment steps.
- …
=> fix: add `name` field to `@stylistic/eslint-plugin` configuration

docs/content/1.packages/0.module.md
This PR makes it clear that the `eslint.config.mjs` file will be generated only once app is started with `nuxi prepare` or `nuxi dev`, and not right away when you run `npx nuxi module add eslint`.
Resolves https://github.com/nuxt/eslint/issues/422#issuecomment-2102653538
=> docs: clarify when config will be generated

docs/content/1.packages/1.config.md
ESLint Module docs has a section on ESLint Stylistic.
- https://eslint.nuxt.com/packages/module#eslint-stylistic
I thought it would be better to have a section for ESLint Stylistic in the `@nuxt/eslint-config` document with different ways to configure ESLint Stylistic.
=> docs(config): add `ESLint Stylistic` in `@nuxt/eslint-config`

docs/content/1.packages/0.module.md
ESLint VSCode extension v3.0.10 has been released which enables flat config by default.
=> docs: update vscode-eslint info

packages/eslint-config/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
n/a
It looks like in `packages/eslint-config`, `@rushstack/eslint-patch` and `tslib` are unused. Those are added respectively in these commits:
- https://github.com/nuxt/eslint/commit/bf74ad93338cf0f6fb3938762ae2fd6fe1f73729: Used by `require('@rushstack/eslint-patch/modern-module-resolution')` but no longer exist now.
- https://github.com/nuxt/eslint/commit/d5f6f66bbcbc24cf785a3097485981dbfce3c1e6: Not sure why `tslib` was added, but it doesn't seem used in `dist` nor part of any deps' peer deps now.
=> fix: remove unused dependencies

docs/content/1.packages/0.module.md
In latest versions this flag is not experimental anymore and might cause confusion.
=> docs: remove experimental flag from flatlist eslint

packages/eslint-config/src/flat/configs/vue.ts
Extends the list of ignored elements in the `vue/singleline-html-element-content-newline` rule to the same one as in https://github.com/nuxt/eslint/blob/cf92de1b586b9f91f57f39b1de53da846d205d80/packages/eslint-config/src/flat/configs/vue.ts#L128-L132
=> fix(eslint-config): extend elements ignored by `vue/singleline-html-element-content-newline`

docs/content/1.packages/2.plugin.md
- closes #556 
The result of correcting `process.client` should be `import.meta.client`, not `import.meta.dev`
=> docs: correct `import.meta.dev` typo

docs/content/1.packages/0.module.md, docs/content/1.packages/1.config.md
Resolves #574 
This PR fixes the documentation examples where the ESLint config override refers to `nuxt/typescript`. Based on the implementation, the correct reference should be `nuxt/typescript/rules` for properly overriding TypeScript-related rules.
The change affects:
- Module documentation in `docs/content/1.packages/0.module.md`
- Config documentation in `docs/content/1.packages/1.config.md`
This small correction ensures that users can correctly customize their TypeScript rules when following the examples in the documentation.
=> docs: replace override rule module name

packages/module/src/modules/config/generate.ts
spotted this when running with deno as well
=> fix: add `node:` prefix to build-in modules

packages/module/src/modules/config/addons/globals.ts
spotted this when trying out the deno node runner (which threw an error) - I'm not sure the previous `.sort()` was doing anything
=> fix: sort imports objects by from + name

packages/eslint-config/src/configs-tooling/jsdoc.ts, packages/eslint-config/src/configs-tooling/regexp.ts, packages/eslint-config/src/configs-tooling/unicorn.ts, packages/eslint-config/src/configs/stylistic.ts, packages/eslint-config/test/__snapshots__/flat-compose.test.ts.snap
This PR fixes an issue where ESLint configurations were applying JavaScript/TypeScript-specific rules to CSS files, causing parsing errors.
When using `@nuxt/eslint-config` with CSS files, ESLint would crash with errors like:
```
TypeError: Error while loading rule '@stylistic/indent': Cannot read properties of undefined (reading 'length')
Occurred while linting assets/css/main.css
```
This happens because several plugin configurations (regexp, stylistic, unicorn, jsdoc) don't specify which file types they should apply to, causing them to run on all files including CSS.
Added explicit file type restrictions using the existing `GLOB_SRC` and `GLOB_VUE` patterns to ensure these plugins only apply to JavaScript, TypeScript, and Vue files:
- `GLOB_SRC`: `**/*.?([cm])[jt]s?(x)` (all JS/TS …
=> fix(eslint-config): add file type restrictions to prevent CSS parsing errors

packages/eslint-config/src/configs/vue.ts
This PR fixes a compatibility issue with eslint-plugin-vue v10+ by replacing the deprecated `allowMultiplePropertiesPerLine` option with the supported `allowAllPropertiesOnSameLine` option in the vue/object-property-newline rule configuration.
When using @nuxt/eslint-config with eslint-plugin-vue v10+, users encounter the following error:
```
Error: eslint-plugin-vue error: 'vue/object-property-newline' rule has unknown option 'allowMultiplePropertiesPerLine'. Allowed options are: 'allowAllPropertiesOnSameLine'.
```
The current configuration uses the deprecated option:
- `allowMultiplePropertiesPerLine` - deprecated in eslint-plugin-vue v10.0.0
- `allowAllPropertiesOnSameLine` - the new supported option
Updated the rule configuration to use only the supported option while maintaining the …
=> fix(eslint-config): replace deprecated vue/object-property-newline option
